language: cpp
sudo: false

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/fortyseveneffects/travis-ci-arduino/master/install.sh)

script:
  - build_main_platforms
  - mkdir build && cd build
  - cmake ..
  - make
  - test/unit-tests/unit-tests

notifications:
  email: false
